//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasySystem.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EasynewsEntities : DbContext
    {
        public EasynewsEntities()
            : base("name=EasynewsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Blacklist> Blacklist { get; set; }
        public virtual DbSet<Comment> Comment { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<Newstype> Newstype { get; set; }
        public virtual DbSet<Read> Read { get; set; }
        public virtual DbSet<Reply> Reply { get; set; }
        public virtual DbSet<Report> Report { get; set; }
        public virtual DbSet<Reporttype> Reporttype { get; set; }
        public virtual DbSet<Score> Score { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
