//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasySystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public int id { get; set; }
        public string text { get; set; }
        public Nullable<int> typeid { get; set; }
        public Nullable<int> userid { get; set; }
        public Nullable<int> newsid { get; set; }
    
        public virtual News News { get; set; }
        public virtual Reporttype Reporttype { get; set; }
        public virtual User User { get; set; }
    }
}
