//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasySystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blacklist
    {
        public int userid { get; set; }
        public System.DateTime starttime { get; set; }
        public System.DateTime endtime { get; set; }
        public string reason { get; set; }
        public int id { get; set; }
    
        public virtual User User { get; set; }
    }
}
