//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasySystem.UI.Controllers
{
    using System;
    using System.Collections.Generic;
    
    using System.Linq;
    using System.Web;
    using System.Web.Mvc;
    using EasySystem.IBLL;
    using EasySystem.Model;
    using EasySystem.BLLContainer;
    	 public class BlacklistController : Controller
        {
            private IBlacklistService BlacklistService = Container.Resolve<IBlacklistService>();
            // GET: Blacklist
            public ActionResult Blacklist()
            {
                List<Blacklist> list = BlacklistService.GetModels(p => true).ToList();
                return View(list);
            }
            public ActionResult Add(Blacklist Blacklist)
            {
                if (BlacklistService.Add(Blacklist))
                {
                    return Redirect("Blacklist");
                }
                else
                {
                    return Content("no");
                }
            }
            public ActionResult Update(Blacklist Blacklist)
            {
                if (BlacklistService.Update(Blacklist))
                {
                    return Redirect("Blacklist");
                }
                else
                {
                    return Content("no");
                }
            }
            public ActionResult Delete(int id)
            {
                var Blacklist = BlacklistService.GetModels(p => p.id == id).FirstOrDefault();
                if (BlacklistService.Delete(Blacklist))
                {
                    return Redirect("Blacklist");
                }
                else
                {
                    return Content("no");
                }
            }
        }
    
}
