//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasySystem.UI.Controllers
{
    using System;
    using System.Collections.Generic;
    
    using System.Linq;
    using System.Web;
    using System.Web.Mvc;
    using EasySystem.IBLL;
    using EasySystem.Model;
    using EasySystem.BLLContainer;
    	 public class CommentController : Controller
        {
            private ICommentService CommentService = Container.Resolve<ICommentService>();
            // GET: Comment
            public ActionResult Comment()
            {
                List<Comment> list = CommentService.GetModels(p => true).ToList();
                return View(list);
            }
            public ActionResult Add(Comment Comment)
            {
                if (CommentService.Add(Comment))
                {
                    return Redirect("Comment");
                }
                else
                {
                    return Content("no");
                }
            }
            public ActionResult Update(Comment Comment)
            {
                if (CommentService.Update(Comment))
                {
                    return Redirect("Comment");
                }
                else
                {
                    return Content("no");
                }
            }
            public ActionResult Delete(int id)
            {
                var Comment = CommentService.GetModels(p => p.id == id).FirstOrDefault();
                if (CommentService.Delete(Comment))
                {
                    return Redirect("Comment");
                }
                else
                {
                    return Content("no");
                }
            }
        }
    
}
