//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasySystem.UI.Controllers
{
    using System;
    using System.Collections.Generic;
    
    using System.Linq;
    using System.Web;
    using System.Web.Mvc;
    using EasySystem.IBLL;
    using EasySystem.Model;
    using EasySystem.BLLContainer;
    	 public class NewsController : Controller
        {
            private INewsService NewsService = Container.Resolve<INewsService>();
            // GET: News
            public ActionResult News()
            {
                List<News> list = NewsService.GetModels(p => true).ToList();
                return View(list);
            }
            public ActionResult Add(News News)
            {
                if (NewsService.Add(News))
                {
                    return Redirect("News");
                }
                else
                {
                    return Content("no");
                }
            }
            public ActionResult Update(News News)
            {
                if (NewsService.Update(News))
                {
                    return Redirect("News");
                }
                else
                {
                    return Content("no");
                }
            }
            public ActionResult Delete(int id)
            {
                var News = NewsService.GetModels(p => p.id == id).FirstOrDefault();
                if (NewsService.Delete(News))
                {
                    return Redirect("News");
                }
                else
                {
                    return Content("no");
                }
            }
        }
    
}
