//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasySystem.UI.Controllers
{
    using System;
    using System.Collections.Generic;
    
    using System.Linq;
    using System.Web;
    using System.Web.Mvc;
    using EasySystem.IBLL;
    using EasySystem.Model;
    using EasySystem.BLLContainer;
    	 public class NewstypeController : Controller
        {
            private INewstypeService NewstypeService = Container.Resolve<INewstypeService>();
            // GET: Newstype
            public ActionResult Newstype()
            {
                List<Newstype> list = NewstypeService.GetModels(p => true).ToList();
                return View(list);
            }
            public ActionResult Add(Newstype Newstype)
            {
                if (NewstypeService.Add(Newstype))
                {
                    return Redirect("Newstype");
                }
                else
                {
                    return Content("no");
                }
            }
            public ActionResult Update(Newstype Newstype)
            {
                if (NewstypeService.Update(Newstype))
                {
                    return Redirect("Newstype");
                }
                else
                {
                    return Content("no");
                }
            }
            public ActionResult Delete(int id)
            {
                var Newstype = NewstypeService.GetModels(p => p.id == id).FirstOrDefault();
                if (NewstypeService.Delete(Newstype))
                {
                    return Redirect("Newstype");
                }
                else
                {
                    return Content("no");
                }
            }
        }
    
}
