//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasySystem.UI.Controllers
{
    using System;
    using System.Collections.Generic;
    
    using System.Linq;
    using System.Web;
    using System.Web.Mvc;
    using EasySystem.IBLL;
    using EasySystem.Model;
    using EasySystem.BLLContainer;
    	 public class ReadController : Controller
        {
            private IReadService ReadService = Container.Resolve<IReadService>();
            // GET: Read
            public ActionResult Read()
            {
                List<Read> list = ReadService.GetModels(p => true).ToList();
                return View(list);
            }
            public ActionResult Add(Read Read)
            {
                if (ReadService.Add(Read))
                {
                    return Redirect("Read");
                }
                else
                {
                    return Content("no");
                }
            }
            public ActionResult Update(Read Read)
            {
                if (ReadService.Update(Read))
                {
                    return Redirect("Read");
                }
                else
                {
                    return Content("no");
                }
            }
            public ActionResult Delete(int id)
            {
                var Read = ReadService.GetModels(p => p.id == id).FirstOrDefault();
                if (ReadService.Delete(Read))
                {
                    return Redirect("Read");
                }
                else
                {
                    return Content("no");
                }
            }
        }
    
}
