//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasySystem.UI.Controllers
{
    using System;
    using System.Collections.Generic;
    
    using System.Linq;
    using System.Web;
    using System.Web.Mvc;
    using EasySystem.IBLL;
    using EasySystem.Model;
    using EasySystem.BLLContainer;
    	 public class ReplyController : Controller
        {
            private IReplyService ReplyService = Container.Resolve<IReplyService>();
            // GET: Reply
            public ActionResult Reply()
            {
                List<Reply> list = ReplyService.GetModels(p => true).ToList();
                return View(list);
            }
            public ActionResult Add(Reply Reply)
            {
                if (ReplyService.Add(Reply))
                {
                    return Redirect("Reply");
                }
                else
                {
                    return Content("no");
                }
            }
            public ActionResult Update(Reply Reply)
            {
                if (ReplyService.Update(Reply))
                {
                    return Redirect("Reply");
                }
                else
                {
                    return Content("no");
                }
            }
            public ActionResult Delete(int id)
            {
                var Reply = ReplyService.GetModels(p => p.id == id).FirstOrDefault();
                if (ReplyService.Delete(Reply))
                {
                    return Redirect("Reply");
                }
                else
                {
                    return Content("no");
                }
            }
        }
    
}
