//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasySystem.UI.Controllers
{
    using System;
    using System.Collections.Generic;
    
    using System.Linq;
    using System.Web;
    using System.Web.Mvc;
    using EasySystem.IBLL;
    using EasySystem.Model;
    using EasySystem.BLLContainer;
    	 public class sysdiagramsController : Controller
        {
            private IsysdiagramsService sysdiagramsService = Container.Resolve<IsysdiagramsService>();
            // GET: sysdiagrams
            public ActionResult sysdiagrams()
            {
                List<sysdiagrams> list = sysdiagramsService.GetModels(p => true).ToList();
                return View(list);
            }
            public ActionResult Add(sysdiagrams sysdiagrams)
            {
                if (sysdiagramsService.Add(sysdiagrams))
                {
                    return Redirect("sysdiagrams");
                }
                else
                {
                    return Content("no");
                }
            }
            public ActionResult Update(sysdiagrams sysdiagrams)
            {
                if (sysdiagramsService.Update(sysdiagrams))
                {
                    return Redirect("sysdiagrams");
                }
                else
                {
                    return Content("no");
                }
            }
            //public ActionResult Delete(int id)
            //{
            //    var sysdiagrams = sysdiagramsService.GetModels(p => p.id == id).FirstOrDefault();
            //    if (sysdiagramsService.Delete(sysdiagrams))
            //    {
            //        return Redirect("sysdiagrams");
            //    }
            //    else
            //    {
            //        return Content("no");
            //    }
            //}
        }
    
}
