//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasySystem.UI.Controllers
{
    using System;
    using System.Collections.Generic;
    
    using System.Linq;
    using System.Web;
    using System.Web.Mvc;
    using EasySystem.IBLL;
    using EasySystem.Model;
    using EasySystem.BLLContainer;
    	 public class UserController : Controller
        {
            private IUserService UserService = Container.Resolve<IUserService>();
            // GET: User
            public ActionResult User()
            {
                List<User> list = UserService.GetModels(p => true).ToList();
                return View(list);
            }
            public ActionResult Add(User User)
            {
                if (UserService.Add(User))
                {
                    return Redirect("User");
                }
                else
                {
                    return Content("no");
                }
            }
            public ActionResult Update(User User)
            {
                if (UserService.Update(User))
                {
                    return Redirect("User");
                }
                else
                {
                    return Content("no");
                }
            }
            public ActionResult Delete(int id)
            {
                var User = UserService.GetModels(p => p.id == id).FirstOrDefault();
                if (UserService.Delete(User))
                {
                    return Redirect("User");
                }
                else
                {
                    return Content("no");
                }
            }
        }
    
}
